<?php

declare(strict_types=1);

namespace MechanicYab\Core\Core;

final class SchemaManager
{
    public const VERSION = 8;
    private const OPTION = 'mechanicyab_schema_version';
    private const LOCK = 'mechanicyab_schema_migration_lock';

    /** @var array<string, callable(string): string> */
    private array $definitions;

    public function __construct()
    {
        $this->definitions = [
            'users' => fn (string $table): string => "CREATE TABLE {$table} (\n                wp_user_id bigint(20) unsigned NOT NULL,\n                mobile varchar(20) NULL,\n                mobile_verified_at datetime NULL,\n                first_name varchar(100) NULL,\n                last_name varchar(100) NULL,\n                status varchar(30) NOT NULL DEFAULT 'active',\n                last_login_at datetime NULL,\n                created_at datetime NOT NULL,\n                updated_at datetime NOT NULL,\n                deleted_at datetime NULL,\n                PRIMARY KEY (wp_user_id),\n                UNIQUE KEY mobile (mobile),\n                KEY status (status),\n                KEY last_login_at (last_login_at)\n            ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;",
            'roles' => fn (string $table): string => "CREATE TABLE {$table} (\n                id bigint(20) unsigned NOT NULL AUTO_INCREMENT,\n                name varchar(100) NOT NULL,\n                slug varchar(100) NOT NULL,\n                description text NULL,\n                created_at datetime NOT NULL,\n                updated_at datetime NOT NULL,\n                PRIMARY KEY (id),\n                UNIQUE KEY name (name),\n                UNIQUE KEY slug (slug)\n            ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;",
            'permissions' => fn (string $table): string => "CREATE TABLE {$table} (\n                id bigint(20) unsigned NOT NULL AUTO_INCREMENT,\n                name varchar(150) NOT NULL,\n                slug varchar(150) NOT NULL,\n                group_name varchar(100) NOT NULL,\n                created_at datetime NOT NULL,\n                updated_at datetime NOT NULL,\n                PRIMARY KEY (id),\n                UNIQUE KEY name (name),\n                UNIQUE KEY slug (slug),\n                KEY group_name (group_name)\n            ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;",
            'role_user' => fn (string $table): string => "CREATE TABLE {$table} (\n                wp_user_id bigint(20) unsigned NOT NULL,\n                role_id bigint(20) unsigned NOT NULL,\n                created_at datetime NOT NULL,\n                PRIMARY KEY (wp_user_id, role_id),\n                KEY role_id (role_id)\n            ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;",
            'permission_role' => fn (string $table): string => "CREATE TABLE {$table} (\n                permission_id bigint(20) unsigned NOT NULL,\n                role_id bigint(20) unsigned NOT NULL,\n                created_at datetime NOT NULL,\n                PRIMARY KEY (permission_id, role_id),\n                KEY role_id (role_id)\n            ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;",
            'user_preferences' => fn (string $table): string => "CREATE TABLE {$table} (\n                wp_user_id bigint(20) unsigned NOT NULL,\n                language varchar(10) NOT NULL DEFAULT 'fa',\n                timezone varchar(64) NOT NULL DEFAULT 'Asia/Tehran',\n                notification_settings longtext NULL,\n                privacy_settings longtext NULL,\n                created_at datetime NOT NULL,\n                updated_at datetime NOT NULL,\n                PRIMARY KEY (wp_user_id)\n            ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;",
            'module_settings' => fn (string $table): string => "CREATE TABLE {$table} (\n                id bigint(20) unsigned NOT NULL AUTO_INCREMENT,\n                module_id varchar(100) NOT NULL,\n                setting_key varchar(150) NOT NULL,\n                setting_value longtext NULL,\n                is_secret tinyint(1) NOT NULL DEFAULT 0,\n                created_at datetime NOT NULL,\n                updated_at datetime NOT NULL,\n                PRIMARY KEY (id),\n                UNIQUE KEY module_setting (module_id, setting_key),\n                KEY module_id (module_id)\n            ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;",
            'module_states' => fn (string $table): string => "CREATE TABLE {$table} (\n                module_id varchar(100) NOT NULL,\n                state varchar(30) NOT NULL DEFAULT 'active',\n                version varchar(30) NOT NULL,\n                reason text NULL,\n                updated_at datetime NOT NULL,\n                PRIMARY KEY (module_id),\n                KEY state (state)\n            ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;",
            'locations' => fn (string $table): string => "CREATE TABLE {$table} (\n                id bigint(20) unsigned NOT NULL AUTO_INCREMENT,\n                parent_id bigint(20) unsigned NULL,\n                type varchar(30) NOT NULL,\n                name varchar(150) NOT NULL,\n                slug varchar(180) NOT NULL,\n                status varchar(30) NOT NULL DEFAULT 'active',\n                sort_order int NOT NULL DEFAULT 0,\n                created_at datetime NOT NULL,\n                updated_at datetime NOT NULL,\n                deleted_at datetime NULL,\n                PRIMARY KEY (id),\n                UNIQUE KEY type_slug (type, slug),\n                KEY parent_id (parent_id),\n                KEY type_status (type, status)\n            ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;",
            'service_categories' => fn (string $table): string => "CREATE TABLE {$table} (\n                id bigint(20) unsigned NOT NULL AUTO_INCREMENT,\n                parent_id bigint(20) unsigned NULL,\n                name varchar(150) NOT NULL,\n                slug varchar(180) NOT NULL,\n                description text NULL,\n                status varchar(30) NOT NULL DEFAULT 'active',\n                sort_order int NOT NULL DEFAULT 0,\n                created_at datetime NOT NULL,\n                updated_at datetime NOT NULL,\n                deleted_at datetime NULL,\n                PRIMARY KEY (id),\n                UNIQUE KEY slug (slug),\n                KEY parent_id (parent_id),\n                KEY status (status)\n            ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;",
            'services' => fn (string $table): string => "CREATE TABLE {$table} (\n                id bigint(20) unsigned NOT NULL AUTO_INCREMENT,\n                category_id bigint(20) unsigned NOT NULL,\n                name varchar(200) NOT NULL,\n                slug varchar(220) NOT NULL,\n                description text NULL,\n                status varchar(30) NOT NULL DEFAULT 'active',\n                sort_order int NOT NULL DEFAULT 0,\n                created_at datetime NOT NULL,\n                updated_at datetime NOT NULL,\n                deleted_at datetime NULL,\n                PRIMARY KEY (id),\n                UNIQUE KEY slug (slug),\n                KEY category_status (category_id, status)\n            ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;",
            'vehicle_brands' => fn (string $table): string => "CREATE TABLE {$table} (\n                id bigint(20) unsigned NOT NULL AUTO_INCREMENT,\n                name varchar(150) NOT NULL,\n                slug varchar(180) NOT NULL,\n                country varchar(100) NULL,\n                status varchar(30) NOT NULL DEFAULT 'active',\n                created_at datetime NOT NULL,\n                updated_at datetime NOT NULL,\n                PRIMARY KEY (id),\n                UNIQUE KEY slug (slug),\n                KEY status (status)\n            ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;",
            'vehicle_models' => fn (string $table): string => "CREATE TABLE {$table} (\n                id bigint(20) unsigned NOT NULL AUTO_INCREMENT,\n                brand_id bigint(20) unsigned NOT NULL,\n                name varchar(150) NOT NULL,\n                slug varchar(180) NOT NULL,\n                status varchar(30) NOT NULL DEFAULT 'active',\n                created_at datetime NOT NULL,\n                updated_at datetime NOT NULL,\n                PRIMARY KEY (id),\n                UNIQUE KEY brand_slug (brand_id, slug),\n                KEY status (status)\n            ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;",
            'vehicle_trims' => fn (string $table): string => "CREATE TABLE {$table} (\n                id bigint(20) unsigned NOT NULL AUTO_INCREMENT,\n                model_id bigint(20) unsigned NOT NULL,\n                name varchar(150) NOT NULL,\n                slug varchar(180) NOT NULL,\n                status varchar(30) NOT NULL DEFAULT 'active',\n                created_at datetime NOT NULL,\n                updated_at datetime NOT NULL,\n                PRIMARY KEY (id),\n                UNIQUE KEY model_slug (model_id, slug),\n                KEY status (status)\n            ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;",
            'mechanics' => fn (string $table): string => "CREATE TABLE {$table} (\n                id bigint(20) unsigned NOT NULL AUTO_INCREMENT,\n                owner_user_id bigint(20) unsigned NOT NULL,\n                name varchar(200) NOT NULL,\n                slug varchar(220) NOT NULL,\n                description text NULL,\n                phone varchar(20) NOT NULL,\n                secondary_phone varchar(20) NULL,\n                whatsapp_phone varchar(20) NULL,\n                website_url varchar(255) NULL,\n                instagram_url varchar(255) NULL,\n                address text NOT NULL,\n                latitude decimal(10,7) NULL,\n                longitude decimal(10,7) NULL,\n                location_id bigint(20) unsigned NOT NULL,\n                status varchar(30) NOT NULL DEFAULT 'draft',\n                publication_status varchar(30) NOT NULL DEFAULT 'draft',\n                verification_status varchar(30) NOT NULL DEFAULT 'unverified',\n                profile_completion_percent tinyint unsigned NOT NULL DEFAULT 0,\n                average_rating decimal(3,2) NOT NULL DEFAULT 0,\n                review_count int unsigned NOT NULL DEFAULT 0,\n                response_rate decimal(5,2) NOT NULL DEFAULT 0,\n                published_at datetime NULL,\n                created_at datetime NOT NULL,\n                updated_at datetime NOT NULL,\n                deleted_at datetime NULL,\n                PRIMARY KEY (id),\n                UNIQUE KEY slug (slug),\n                KEY owner_user_id (owner_user_id),\n                KEY location_id (location_id),\n                KEY publication_status (publication_status),\n                KEY verification_status (verification_status),\n                KEY rating_count (average_rating, review_count)\n            ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;",
            'mechanic_locations' => fn (string $table): string => "CREATE TABLE {$table} (\n                id bigint(20) unsigned NOT NULL AUTO_INCREMENT,\n                mechanic_id bigint(20) unsigned NOT NULL,\n                location_id bigint(20) unsigned NOT NULL,\n                is_primary tinyint(1) NOT NULL DEFAULT 1,\n                created_at datetime NOT NULL,\n                updated_at datetime NOT NULL,\n                PRIMARY KEY (id),\n                UNIQUE KEY mechanic_location (mechanic_id, location_id),\n                KEY location_id (location_id)\n            ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;",
            'mechanic_business_profiles' => fn (string $table): string => "CREATE TABLE {$table} (\n                id bigint(20) unsigned NOT NULL AUTO_INCREMENT,\n                mechanic_id bigint(20) unsigned NOT NULL,\n                business_type varchar(100) NULL,\n                established_year smallint NULL,\n                license_reference varchar(150) NULL,\n                business_description text NULL,\n                parking_available tinyint(1) NULL,\n                mobile_service tinyint(1) NOT NULL DEFAULT 0,\n                emergency_service tinyint(1) NOT NULL DEFAULT 0,\n                created_at datetime NOT NULL,\n                updated_at datetime NOT NULL,\n                PRIMARY KEY (id),\n                UNIQUE KEY mechanic_id (mechanic_id)\n            ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;",
            'mechanic_verifications' => fn (string $table): string => "CREATE TABLE {$table} (\n                id bigint(20) unsigned NOT NULL AUTO_INCREMENT,\n                mechanic_id bigint(20) unsigned NOT NULL,\n                type varchar(50) NOT NULL,\n                status varchar(30) NOT NULL DEFAULT 'pending',\n                submitted_by bigint(20) unsigned NOT NULL,\n                reviewed_by bigint(20) unsigned NULL,\n                notes text NULL,\n                verified_at datetime NULL,\n                expires_at datetime NULL,\n                created_at datetime NOT NULL,\n                updated_at datetime NOT NULL,\n                PRIMARY KEY (id),\n                KEY mechanic_status (mechanic_id, status),\n                KEY expires_at (expires_at)\n            ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;",
            'mechanic_hours' => fn (string $table): string => "CREATE TABLE {$table} (\n                id bigint(20) unsigned NOT NULL AUTO_INCREMENT,\n                mechanic_id bigint(20) unsigned NOT NULL,\n                day_of_week tinyint unsigned NOT NULL,\n                is_open tinyint(1) NOT NULL DEFAULT 1,\n                open_time time NULL,\n                close_time time NULL,\n                break_start time NULL,\n                break_end time NULL,\n                created_at datetime NOT NULL,\n                updated_at datetime NOT NULL,\n                PRIMARY KEY (id),\n                UNIQUE KEY mechanic_day (mechanic_id, day_of_week)\n            ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;",
            'mechanic_special_hours' => fn (string $table): string => "CREATE TABLE {$table} (\n                id bigint(20) unsigned NOT NULL AUTO_INCREMENT,\n                mechanic_id bigint(20) unsigned NOT NULL,\n                date date NOT NULL,\n                is_closed tinyint(1) NOT NULL DEFAULT 0,\n                open_time time NULL,\n                close_time time NULL,\n                reason varchar(255) NULL,\n                created_at datetime NOT NULL,\n                updated_at datetime NOT NULL,\n                PRIMARY KEY (id),\n                UNIQUE KEY mechanic_date (mechanic_id, date)\n            ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;",
            'mechanic_services' => fn (string $table): string => "CREATE TABLE {$table} (\n                id bigint(20) unsigned NOT NULL AUTO_INCREMENT,\n                mechanic_id bigint(20) unsigned NOT NULL,\n                service_id bigint(20) unsigned NOT NULL,\n                description text NULL,\n                duration_minutes int unsigned NULL,\n                status varchar(30) NOT NULL DEFAULT 'active',\n                created_at datetime NOT NULL,\n                updated_at datetime NOT NULL,\n                PRIMARY KEY (id),\n                UNIQUE KEY mechanic_service (mechanic_id, service_id),\n                KEY service_id (service_id)\n            ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;",
            'mechanic_service_vehicles' => fn (string $table): string => "CREATE TABLE {$table} (\n                id bigint(20) unsigned NOT NULL AUTO_INCREMENT,\n                mechanic_service_id bigint(20) unsigned NOT NULL,\n                brand_id bigint(20) unsigned NULL,\n                model_id bigint(20) unsigned NULL,\n                trim_id bigint(20) unsigned NULL,\n                created_at datetime NOT NULL,\n                updated_at datetime NOT NULL,\n                PRIMARY KEY (id),\n                KEY mechanic_service_id (mechanic_service_id),\n                KEY vehicle_match (brand_id, model_id, trim_id)\n            ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;",
            'mechanic_prices' => fn (string $table): string => "CREATE TABLE {$table} (\n                id bigint(20) unsigned NOT NULL AUTO_INCREMENT,\n                mechanic_id bigint(20) unsigned NOT NULL,\n                service_id bigint(20) unsigned NOT NULL,\n                brand_id bigint(20) unsigned NULL,\n                model_id bigint(20) unsigned NULL,\n                trim_id bigint(20) unsigned NULL,\n                price_amount decimal(15,2) NULL,\n                price_min decimal(15,2) NULL,\n                price_max decimal(15,2) NULL,\n                currency varchar(10) NOT NULL DEFAULT 'IRR',\n                description text NULL,\n                status varchar(30) NOT NULL DEFAULT 'draft',\n                published_at datetime NULL,\n                created_at datetime NOT NULL,\n                updated_at datetime NOT NULL,\n                PRIMARY KEY (id),\n                KEY mechanic_service (mechanic_id, service_id),\n                KEY vehicle_match (mechanic_id, brand_id, model_id),\n                KEY status (status)\n            ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;",
            'media' => fn (string $table): string => "CREATE TABLE {$table} (\n                id bigint(20) unsigned NOT NULL AUTO_INCREMENT,\n                wp_attachment_id bigint(20) unsigned NULL,\n                disk varchar(50) NOT NULL,\n                path varchar(500) NOT NULL,\n                file_name varchar(255) NOT NULL,\n                mime_type varchar(100) NOT NULL,\n                size_bytes bigint(20) unsigned NOT NULL DEFAULT 0,\n                alt_text varchar(255) NULL,\n                uploaded_by bigint(20) unsigned NOT NULL,\n                created_at datetime NOT NULL,\n                updated_at datetime NOT NULL,\n                deleted_at datetime NULL,\n                PRIMARY KEY (id),\n                KEY wp_attachment_id (wp_attachment_id),\n                KEY uploaded_by (uploaded_by)\n            ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;",
            'mechanic_gallery' => fn (string $table): string => "CREATE TABLE {$table} (\n                id bigint(20) unsigned NOT NULL AUTO_INCREMENT,\n                mechanic_id bigint(20) unsigned NOT NULL,\n                media_id bigint(20) unsigned NOT NULL,\n                category varchar(50) NULL,\n                caption varchar(255) NULL,\n                sort_order int NOT NULL DEFAULT 0,\n                is_cover tinyint(1) NOT NULL DEFAULT 0,\n                created_at datetime NOT NULL,\n                updated_at datetime NOT NULL,\n                PRIMARY KEY (id),\n                UNIQUE KEY mechanic_media (mechanic_id, media_id),\n                KEY mechanic_order (mechanic_id, sort_order)\n            ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;",
            'mechanic_employees' => fn (string $table): string => "CREATE TABLE {$table} (\n                id bigint(20) unsigned NOT NULL AUTO_INCREMENT,\n                mechanic_id bigint(20) unsigned NOT NULL,\n                name varchar(150) NOT NULL,\n                position varchar(150) NULL,\n                specialty varchar(200) NULL,\n                experience_years smallint unsigned NULL,\n                bio text NULL,\n                status varchar(30) NOT NULL DEFAULT 'active',\n                sort_order int NOT NULL DEFAULT 0,\n                created_at datetime NOT NULL,\n                updated_at datetime NOT NULL,\n                deleted_at datetime NULL,\n                PRIMARY KEY (id),\n                KEY mechanic_status (mechanic_id, status)\n            ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;",
            'mechanic_social_profiles' => fn (string $table): string => "CREATE TABLE {$table} (\n                id bigint(20) unsigned NOT NULL AUTO_INCREMENT,\n                mechanic_id bigint(20) unsigned NOT NULL,\n                platform varchar(50) NOT NULL,\n                url varchar(255) NOT NULL,\n                username varchar(150) NULL,\n                status varchar(30) NOT NULL DEFAULT 'active',\n                created_at datetime NOT NULL,\n                updated_at datetime NOT NULL,\n                PRIMARY KEY (id),\n                UNIQUE KEY mechanic_platform (mechanic_id, platform)\n            ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;",
            'reviews' => fn (string $table): string => "CREATE TABLE {$table} (\n                id bigint(20) unsigned NOT NULL AUTO_INCREMENT,\n                mechanic_id bigint(20) unsigned NOT NULL,\n                wp_user_id bigint(20) unsigned NOT NULL,\n                vehicle_id bigint(20) unsigned NULL,\n                service_id bigint(20) unsigned NULL,\n                rating tinyint unsigned NOT NULL,\n                quality_rating tinyint unsigned NULL,\n                price_rating tinyint unsigned NULL,\n                speed_rating tinyint unsigned NULL,\n                behavior_rating tinyint unsigned NULL,\n                title varchar(255) NULL,\n                body text NOT NULL,\n                status varchar(30) NOT NULL DEFAULT 'active',\n                moderation_status varchar(30) NOT NULL DEFAULT 'pending',\n                is_verified_visit tinyint(1) NOT NULL DEFAULT 0,\n                published_at datetime NULL,\n                created_at datetime NOT NULL,\n                updated_at datetime NOT NULL,\n                deleted_at datetime NULL,\n                PRIMARY KEY (id),\n                KEY mechanic_moderation (mechanic_id, moderation_status),\n                KEY wp_user_id (wp_user_id),\n                KEY published_at (published_at)\n            ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;",
            'review_replies' => fn (string $table): string => "CREATE TABLE {$table} (\n                id bigint(20) unsigned NOT NULL AUTO_INCREMENT,\n                review_id bigint(20) unsigned NOT NULL,\n                mechanic_id bigint(20) unsigned NOT NULL,\n                body text NOT NULL,\n                status varchar(30) NOT NULL DEFAULT 'active',\n                created_at datetime NOT NULL,\n                updated_at datetime NOT NULL,\n                PRIMARY KEY (id),\n                UNIQUE KEY review_id (review_id),\n                KEY mechanic_id (mechanic_id)\n            ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;",
            'review_reports' => fn (string $table): string => "CREATE TABLE {$table} (\n                id bigint(20) unsigned NOT NULL AUTO_INCREMENT,\n                review_id bigint(20) unsigned NOT NULL,\n                reported_by bigint(20) unsigned NOT NULL,\n                reason_code varchar(50) NOT NULL,\n                description text NULL,\n                status varchar(30) NOT NULL DEFAULT 'open',\n                resolved_by bigint(20) unsigned NULL,\n                resolved_at datetime NULL,\n                created_at datetime NOT NULL,\n                updated_at datetime NOT NULL,\n                PRIMARY KEY (id),\n                KEY review_status (review_id, status),\n                KEY reported_by (reported_by)\n            ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;",
            'moderation_cases' => fn (string $table): string => "CREATE TABLE {$table} (\n                id bigint(20) unsigned NOT NULL AUTO_INCREMENT,\n                entity_type varchar(50) NOT NULL,\n                entity_id bigint(20) unsigned NOT NULL,\n                reported_by bigint(20) unsigned NULL,\n                reason_code varchar(100) NOT NULL,\n                description text NULL,\n                status varchar(30) NOT NULL DEFAULT 'open',\n                assigned_to bigint(20) unsigned NULL,\n                resolved_by bigint(20) unsigned NULL,\n                resolved_at datetime NULL,\n                created_at datetime NOT NULL,\n                updated_at datetime NOT NULL,\n                PRIMARY KEY (id),\n                KEY entity (entity_type, entity_id),\n                KEY status (status)\n            ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;",
            'otp_challenges' => fn (string $table): string => "CREATE TABLE {$table} (\n                id bigint(20) unsigned NOT NULL AUTO_INCREMENT,\n                mobile_hash char(64) NOT NULL,\n                otp_hash char(64) NOT NULL,\n                purpose varchar(30) NOT NULL,\n                attempts tinyint unsigned NOT NULL DEFAULT 0,\n                max_attempts tinyint unsigned NOT NULL DEFAULT 5,\n                status varchar(30) NOT NULL DEFAULT 'active',\n                expires_at datetime NOT NULL,\n                consumed_at datetime NULL,\n                last_sent_at datetime NOT NULL,\n                provider_reference varchar(255) NULL,\n                created_at datetime NOT NULL,\n                PRIMARY KEY (id),\n                KEY mobile_purpose (mobile_hash, purpose, status),\n                KEY expires_at (expires_at)\n            ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;",
            'favorites' => fn (string $table): string => "CREATE TABLE {$table} (\n                id bigint(20) unsigned NOT NULL AUTO_INCREMENT,\n                wp_user_id bigint(20) unsigned NOT NULL,\n                entity_type varchar(50) NOT NULL,\n                entity_id bigint(20) unsigned NOT NULL,\n                created_at datetime NOT NULL,\n                PRIMARY KEY (id),\n                UNIQUE KEY user_entity (wp_user_id, entity_type, entity_id),\n                KEY entity (entity_type, entity_id)\n            ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;",
            'user_vehicles' => fn (string $table): string => "CREATE TABLE {$table} (\n                id bigint(20) unsigned NOT NULL AUTO_INCREMENT,\n                wp_user_id bigint(20) unsigned NOT NULL,\n                brand_id bigint(20) unsigned NOT NULL,\n                model_id bigint(20) unsigned NOT NULL,\n                trim_id bigint(20) unsigned NULL,\n                nickname varchar(100) NULL,\n                manufacture_year smallint NULL,\n                production_year smallint NULL,\n                current_mileage int unsigned NULL,\n                license_plate_encrypted text NULL,\n                vin_encrypted text NULL,\n                status varchar(30) NOT NULL DEFAULT 'active',\n                is_primary tinyint(1) NOT NULL DEFAULT 0,\n                created_at datetime NOT NULL,\n                updated_at datetime NOT NULL,\n                deleted_at datetime NULL,\n                PRIMARY KEY (id),\n                KEY wp_user_id (wp_user_id),\n                KEY vehicle_match (brand_id, model_id, trim_id)\n            ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;",
            'vehicle_service_records' => fn (string $table): string => "CREATE TABLE {$table} (\n                id bigint(20) unsigned NOT NULL AUTO_INCREMENT,\n                vehicle_id bigint(20) unsigned NOT NULL,\n                mechanic_id bigint(20) unsigned NULL,\n                service_id bigint(20) unsigned NULL,\n                service_date date NOT NULL,\n                mileage int unsigned NULL,\n                cost_amount decimal(15,2) NULL,\n                currency varchar(10) NOT NULL DEFAULT 'IRR',\n                notes text NULL,\n                created_by bigint(20) unsigned NOT NULL,\n                created_at datetime NOT NULL,\n                updated_at datetime NOT NULL,\n                deleted_at datetime NULL,\n                PRIMARY KEY (id),\n                KEY vehicle_date (vehicle_id, service_date)\n            ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;",
            'vehicle_reminders' => fn (string $table): string => "CREATE TABLE {$table} (\n                id bigint(20) unsigned NOT NULL AUTO_INCREMENT,\n                vehicle_id bigint(20) unsigned NOT NULL,\n                service_id bigint(20) unsigned NULL,\n                title varchar(255) NOT NULL,\n                description text NULL,\n                due_date date NULL,\n                due_mileage int unsigned NULL,\n                status varchar(30) NOT NULL DEFAULT 'active',\n                completed_at datetime NULL,\n                created_at datetime NOT NULL,\n                updated_at datetime NOT NULL,\n                PRIMARY KEY (id),\n                KEY vehicle_status (vehicle_id, status),\n                KEY due_date (due_date)\n            ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;",
            'notifications' => fn (string $table): string => "CREATE TABLE {$table} (\n                id bigint(20) unsigned NOT NULL AUTO_INCREMENT,\n                wp_user_id bigint(20) unsigned NOT NULL,\n                type varchar(80) NOT NULL,\n                title varchar(255) NOT NULL,\n                body text NOT NULL,\n                data longtext NULL,\n                read_at datetime NULL,\n                created_at datetime NOT NULL,\n                PRIMARY KEY (id),\n                KEY user_read (wp_user_id, read_at),\n                KEY user_created (wp_user_id, created_at)\n            ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;",
            'notification_deliveries' => fn (string $table): string => "CREATE TABLE {$table} (\n                id bigint(20) unsigned NOT NULL AUTO_INCREMENT,\n                notification_id bigint(20) unsigned NOT NULL,\n                channel varchar(30) NOT NULL,\n                status varchar(30) NOT NULL DEFAULT 'pending',\n                provider_reference varchar(255) NULL,\n                sent_at datetime NULL,\n                failed_at datetime NULL,\n                error_code varchar(100) NULL,\n                created_at datetime NOT NULL,\n                updated_at datetime NOT NULL,\n                PRIMARY KEY (id),\n                UNIQUE KEY notification_channel (notification_id, channel),\n                KEY status (status)\n            ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;",
            'analytics_events' => fn (string $table): string => "CREATE TABLE {$table} (\n                id bigint(20) unsigned NOT NULL AUTO_INCREMENT,\n                event_name varchar(120) NOT NULL,\n                cta_id varchar(80) NULL,\n                entity_type varchar(50) NULL,\n                entity_id bigint(20) unsigned NULL,\n                page_type varchar(100) NULL,\n                city_id bigint(20) unsigned NULL,\n                neighborhood_id bigint(20) unsigned NULL,\n                service_id bigint(20) unsigned NULL,\n                vehicle_model_id bigint(20) unsigned NULL,\n                session_hash char(64) NULL,\n                wp_user_id bigint(20) unsigned NULL,\n                device_type varchar(30) NULL,\n                outcome varchar(30) NULL,\n                occurred_at datetime NOT NULL,\n                dedupe_key char(64) NOT NULL,\n                created_at datetime NOT NULL,\n                PRIMARY KEY (id),\n                UNIQUE KEY dedupe_key (dedupe_key),\n                KEY event_time (event_name, occurred_at),\n                KEY entity (entity_type, entity_id),\n                KEY user_time (wp_user_id, occurred_at)\n            ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;",
            'analytics_hourly_metrics' => fn (string $table): string => "CREATE TABLE {$table} (\n                id bigint(20) unsigned NOT NULL AUTO_INCREMENT,\n                metric_key varchar(120) NOT NULL,\n                bucket_start datetime NOT NULL,\n                dimensions longtext NULL,\n                metric_value decimal(18,4) NOT NULL DEFAULT 0,\n                updated_at datetime NOT NULL,\n                PRIMARY KEY (id),\n                UNIQUE KEY metric_bucket (metric_key, bucket_start),\n                KEY bucket_start (bucket_start)\n            ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;",
            'analytics_daily_metrics' => fn (string $table): string => "CREATE TABLE {$table} (\n                id bigint(20) unsigned NOT NULL AUTO_INCREMENT,\n                metric_key varchar(120) NOT NULL,\n                bucket_date date NOT NULL,\n                dimensions longtext NULL,\n                metric_value decimal(18,4) NOT NULL DEFAULT 0,\n                updated_at datetime NOT NULL,\n                PRIMARY KEY (id),\n                UNIQUE KEY metric_date (metric_key, bucket_date),\n                KEY bucket_date (bucket_date)\n            ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;",
            'payments' => fn (string $table): string => "CREATE TABLE {$table} (\n                id bigint(20) unsigned NOT NULL AUTO_INCREMENT,\n                payer_user_id bigint(20) unsigned NOT NULL,\n                order_key varchar(100) NOT NULL,\n                subscription_id bigint(20) unsigned NULL,\n                advertisement_id bigint(20) unsigned NULL,\n                amount decimal(15,2) NOT NULL,\n                currency varchar(10) NOT NULL DEFAULT 'IRR',\n                gateway varchar(50) NOT NULL,\n                gateway_reference varchar(255) NULL,\n                status varchar(30) NOT NULL DEFAULT 'pending',\n                idempotency_key varchar(255) NOT NULL,\n                paid_at datetime NULL,\n                created_at datetime NOT NULL,\n                updated_at datetime NOT NULL,\n                PRIMARY KEY (id),\n                UNIQUE KEY order_key (order_key),\n                UNIQUE KEY idempotency_key (idempotency_key),\n                KEY payer_status (payer_user_id, status),\n                KEY gateway_reference (gateway_reference)\n            ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;",
            'payment_transactions' => fn (string $table): string => "CREATE TABLE {$table} (\n                id bigint(20) unsigned NOT NULL AUTO_INCREMENT,\n                payment_id bigint(20) unsigned NOT NULL,\n                gateway_transaction_id varchar(255) NULL,\n                gateway_status varchar(100) NULL,\n                raw_reference varchar(255) NULL,\n                verification_status varchar(30) NOT NULL DEFAULT 'pending',\n                verified_at datetime NULL,\n                response_payload longtext NULL,\n                created_at datetime NOT NULL,\n                updated_at datetime NOT NULL,\n                PRIMARY KEY (id),\n                KEY payment_status (payment_id, verification_status),\n                KEY gateway_transaction (gateway_transaction_id)\n            ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;",
            'refunds' => fn (string $table): string => "CREATE TABLE {$table} (\n                id bigint(20) unsigned NOT NULL AUTO_INCREMENT,\n                payment_id bigint(20) unsigned NOT NULL,\n                amount decimal(15,2) NOT NULL,\n                currency varchar(10) NOT NULL DEFAULT 'IRR',\n                reason varchar(255) NOT NULL,\n                status varchar(30) NOT NULL DEFAULT 'requested',\n                gateway_reference varchar(255) NULL,\n                processed_at datetime NULL,\n                created_at datetime NOT NULL,\n                updated_at datetime NOT NULL,\n                PRIMARY KEY (id),\n                KEY payment_status (payment_id, status)\n            ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;",
        ];
    }

    /** @return array<string, string> */
    public function tableNames(?string $prefix = null): array
    {
        $prefix ??= $this->prefix();
        $tables = [];
        foreach (array_keys($this->definitions) as $name) {
            $tables[$name] = $prefix . 'my_' . $name;
        }
        return $tables;
    }

    public function migrate(): void
    {
        global $wpdb;
        if (!isset($wpdb) || !is_object($wpdb)) {
            throw new \RuntimeException('WordPress database runtime is unavailable.');
        }
        if ($this->currentVersion() >= self::VERSION) {
            return;
        }
        if (!$this->acquireLock()) {
            throw new \RuntimeException('Schema migration is already in progress.');
        }
        if (!function_exists('dbDelta')) {
            require_once ABSPATH . 'wp-admin/includes/upgrade.php';
        }
        try {
            foreach ($this->definitions as $name => $definition) {
                dbDelta($definition($this->prefix() . 'my_' . $name));
            }
            if (function_exists('update_option')) {
                update_option(self::OPTION, self::VERSION, false);
            }
        } catch (\Throwable $exception) {
            $this->releaseLock();
            throw new \RuntimeException('Schema migration failed; version was not advanced.', 0, $exception);
        }
        $this->releaseLock();
    }

    /** @return array{destructive: bool, actions: list<string>} */
    public function rollbackPlan(): array
    {
        return [
            'destructive' => false,
            'actions' => ['Restore the previous code release and rerun verification.', 'Do not drop or reset Stage 2/3 tables.'],
        ];
    }

    private function acquireLock(): bool
    {
        if (!function_exists('add_option')) {
            return true;
        }
        return (bool) add_option(self::LOCK, time(), '', 'no');
    }

    private function releaseLock(): void
    {
        if (function_exists('delete_option')) {
            delete_option(self::LOCK);
        }
    }

    public function currentVersion(): int
    {
        return function_exists('get_option') ? (int) get_option(self::OPTION, 0) : 0;
    }

    /** @return list<string> */
    public function pendingMigrations(): array
    {
        return match (true) {
            $this->currentVersion() < 1 => ['stage-2-core-schema-v1', 'stage-3-reference-schema-v2', 'stage-4-mechanics-schema-v3', 'stage-4-mechanics-support-v4', 'stage-7-reviews-trust-v5', 'stage-8-auth-users-v6', 'stage-9-analytics-v7', 'stage-10-financial-v8'],
            $this->currentVersion() < 2 => ['stage-3-reference-schema-v2', 'stage-4-mechanics-schema-v3', 'stage-4-mechanics-support-v4', 'stage-7-reviews-trust-v5', 'stage-8-auth-users-v6', 'stage-9-analytics-v7', 'stage-10-financial-v8'],
            $this->currentVersion() < 3 => ['stage-4-mechanics-schema-v3', 'stage-4-mechanics-support-v4', 'stage-7-reviews-trust-v5', 'stage-8-auth-users-v6', 'stage-9-analytics-v7', 'stage-10-financial-v8'],
            $this->currentVersion() < 4 => ['stage-4-mechanics-support-v4', 'stage-7-reviews-trust-v5', 'stage-8-auth-users-v6', 'stage-9-analytics-v7', 'stage-10-financial-v8'],
            $this->currentVersion() < 5 => ['stage-7-reviews-trust-v5', 'stage-8-auth-users-v6', 'stage-9-analytics-v7', 'stage-10-financial-v8'],
            $this->currentVersion() < 6 => ['stage-8-auth-users-v6', 'stage-9-analytics-v7', 'stage-10-financial-v8'],
            $this->currentVersion() < 7 => ['stage-9-analytics-v7', 'stage-10-financial-v8'],
            $this->currentVersion() < 7 => ['stage-9-analytics-v7', 'stage-10-financial-v8'],
            $this->currentVersion() < 8 => ['stage-10-financial-v8'],
            default => [],
        };
    }

    /** @return array<string, string> */
    public function identityContract(): array
    {
        return [
            'canonical_table' => 'wp_users',
            'canonical_key' => 'ID',
            'profile_table' => 'my_users',
            'profile_key' => 'wp_user_id',
            'role_link_key' => 'wp_user_id',
            'preference_key' => 'wp_user_id',
        ];
    }

    /** @return array{status: string, version: int, tables: array<string, string>} */
    public function healthReport(): array
    {
        return [
            'status' => $this->currentVersion() >= self::VERSION ? 'healthy' : 'pending',
            'version' => $this->currentVersion(),
            'tables' => $this->tableNames(),
        ];
    }

    private function prefix(): string
    {
        global $wpdb;
        if (isset($wpdb) && isset($wpdb->prefix)) {
            return (string) $wpdb->prefix;
        }
        return 'wp_';
    }
}
